---
- name: iLO and BIOS configuration through RestAPI
  hosts: all
  connection: local
  gather_facts: False

  vars:
    - bios_revert_default: False
    - bios_boot_mode: LegacyBios
    - bios_power_profile: MaxPerf
    - bios_power_regulator: StaticHighPerf
    - reset_server: False

  roles:
    - ilorest
